# Base configs
baseurl: ""
url: "http://martinplut.photography.me/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Martin Plut"
subtitle: "Progled na svet skozi moje oči"
author: "Martin Plut"
bio: "I am an amateur photographer from the San Francisco Bay Area. "
publicise: "Looking for prints or to schedule a shoot? Email me at martinplutphoto@gmail.com"
web_design: "A man by the name of AJ"
social_urls:
  Facebook: "https://www.facebook.com/martinplutphotog"
  Instagram: "https://www.instagram.com/martinplutphotog"
  Instagram: "https://www.instagram.com/martin.dng"
  500px: "https://500px.com/martinplutphotography"
  Linkedin: "https://in.linkedin.com/in/martin-plut-838926115"
